# compose.yaml

version: '3.8'

services:
  # O serviço do nosso backend
  server:
    image: seniorsystem_server:latest
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: "info"
    depends_on:
      # MODIFICADO: Agora o 'server' depende da condição de saúde do 'db'
      db:
        condition: service_healthy

  # O serviço do banco de dados
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    # [NOVO] Seção de verificação de saúde
    healthcheck:
      # Comando que o Podman executará para verificar se o MySQL está pronto.
      # Ele tenta executar um comando 'ping' no servidor MySQL.
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s   # Verifica a cada 10 segundos.
      timeout: 5s     # Considera a verificação falha se demorar mais de 5 segundos.
      retries: 5      # Tenta 5 vezes antes de marcar o contêiner como "unhealthy".

volumes:
  mysql_data: